/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BundlesIndexRouteImport } from './routes/bundles.index'
import { Route as BundlesIdRouteImport } from './routes/bundles.$id'
import { Route as BundlesNewRouteImport } from './routes/bundles.new'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkIdRouteImport } from './routes/work.$id'
import { Route as WorkNewRouteImport } from './routes/work.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIndexRoute = BundlesIndexRouteImport.update({
  id: '/bundles/',
  path: '/bundles/',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesIdRoute = BundlesIdRouteImport.update({
  id: '/bundles/$id',
  path: '/bundles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesNewRoute = BundlesNewRouteImport.update({
  id: '/bundles/new',
  path: '/bundles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIdRoute = WorkIdRouteImport.update({
  id: '/work/$id',
  path: '/work/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkNewRoute = WorkNewRouteImport.update({
  id: '/work/new',
  path: '/work/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/bundles/$id': typeof BundlesIdRoute
  '/bundles/new': typeof BundlesNewRoute
  '/work/$id': typeof WorkIdRoute
  '/work/new': typeof WorkNewRoute
  '/bundles/': typeof BundlesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/bundles/$id': typeof BundlesIdRoute
  '/bundles/new': typeof BundlesNewRoute
  '/work/$id': typeof WorkIdRoute
  '/work/new': typeof WorkNewRoute
  '/bundles': typeof BundlesIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/bundles/$id': typeof BundlesIdRoute
  '/bundles/new': typeof BundlesNewRoute
  '/work/$id': typeof WorkIdRoute
  '/work/new': typeof WorkNewRoute
  '/bundles/': typeof BundlesIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/bundles/$id'
    | '/bundles/new'
    | '/work/$id'
    | '/work/new'
    | '/bundles/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/bundles/$id'
    | '/bundles/new'
    | '/work/$id'
    | '/work/new'
    | '/bundles'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/bundles/$id'
    | '/bundles/new'
    | '/work/$id'
    | '/work/new'
    | '/bundles/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  BundlesIdRoute: typeof BundlesIdRoute
  BundlesNewRoute: typeof BundlesNewRoute
  WorkIdRoute: typeof WorkIdRoute
  WorkNewRoute: typeof WorkNewRoute
  BundlesIndexRoute: typeof BundlesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/': {
      id: '/bundles/'
      path: '/bundles'
      fullPath: '/bundles/'
      preLoaderRoute: typeof BundlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/$id': {
      id: '/bundles/$id'
      path: '/bundles/$id'
      fullPath: '/bundles/$id'
      preLoaderRoute: typeof BundlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles/new': {
      id: '/bundles/new'
      path: '/bundles/new'
      fullPath: '/bundles/new'
      preLoaderRoute: typeof BundlesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$id': {
      id: '/work/$id'
      path: '/work/$id'
      fullPath: '/work/$id'
      preLoaderRoute: typeof WorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/new': {
      id: '/work/new'
      path: '/work/new'
      fullPath: '/work/new'
      preLoaderRoute: typeof WorkNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  BundlesIdRoute: BundlesIdRoute,
  BundlesNewRoute: BundlesNewRoute,
  WorkIdRoute: WorkIdRoute,
  WorkNewRoute: WorkNewRoute,
  BundlesIndexRoute: BundlesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
